
function newMessage() {
    var randomNumber = Math.floor(Math.random() * ([
        'i gotta know.',
        'things are so complicated',
        'i think about you all the time.',
        'i want to escape with you to another dimension.',
        'finding the right words...',
        'so comfortable with you...',
        'trust',
        'you are my one and only.',
        'tryna smoke',
        'flow',
        'keeping myself healthy',
        'unfinished business...',
        'im afraid you wont accept me.',
        'i want to hold you in my arms and feel your skin next to mine.',
        'idc anymore, im calling texting you.',
        'cheap thrills?',
        'im aware i took advantage of the situation.',
        'trying to make this right.',
        'triggered.',
        'reflecting on what i did wrong and everythng you said...',
        'i was scared.',
        'not interested in being with anyone but you.',
        '1111',
        '222',
        'i want you to touch yourself and think of us.',
        'these niggas wont love you like i can.',
        'think of me.',
        'i want you so bad.',
        'the way you touch me makes me high.',
        'touching myself thinking of you.',
        'licking you all over.',
        'let me taste you again.',
        'you showed me real love.',
        'i think about all those things you said.',
        'did you mean it when you said that its mine?',
        'your body is out of this world',
        'the love i feel for you is real.',
        'the universe shows me signs that this connection is real.',
        'my spirits show me that you are the one.',
        'healing',
        'manifestation of goals',
        'delay, not denial',
        'wish coming true',
        'loving you is easy.',
        'you are so sensitive, i dont want to cause you harm.',
        'put me in my place.',
        'your level of kindness is rare.',
        'i miss how cute you are.',
        'your smile lights me up.',
        'the way you laugh...',
        'lucky femme',
        'ego boost',
        'i wanted you to chase me.',
        'will you accept or reject me?',
        'can i come over?',
        'i am ready.',
        'making room for us.',
        'i want to commit to us and prioritize this.',
        'twin flame, we belong together.',
        'i am worthy of this love.',
        'love me.',
        'dont you want me?',
        'im not upset.',
        'i will never forget that day.',
        'seeing you naked...',
        'swimming in those eyes...',
        'all i want is you.',
        'reaching out soon...',
        'spirit evolution',
        'unexpected changes',
        'i want to be absolutely sure that i am ready.',
        'i adore you and honor you.',
        'i cherish every moment we had together.',
        'real love',
        'you got me wrapped around your finger.',
        '555',
        'empress',
        'focus',
        'divine counterpart',
        'lovers',
        'star',
        'temperence',
        'your patience is a virtue.',
        'angelic support',
        '7',
        'divine intervention',
        'careful who you talk to about this connection.',
        'waking up next to you...',
        'faith in us',
        'teach me how to love.',
        'so sexy when you take control.',
        'i am waiting for the right time.',
        'i miss us.',
        'i miss you.',
        'si mami.',
        'you smell so good.',
        'kissing you...',
        'you make me a better person.',
        'making plans to come toward you...',
        'couldnt love you more.',
        'i am ashamed of how i treated you.',
        'dream girl',
        'i dream of you.',
        'i want to support you.',
        'no',
        'yes',
        'time and money',
        'i want to be good enough to pursue this.',
        'i dont want to hurt you.',
        'i know i have been inconsistent.',
        'you could have anyone you want.',
        'you deserve better than the way i did you.',
        'i ghosted and i regret it.'
    ].length));
    document.getElementById('messageDisplay').innerHTML = [
        'i gotta know.',
        'things are so complicated',
        'i think about you all the time.',
        'i want to escape with you to another dimension.',
        'so comfortable with you...',
        'finding the right words',
        'trust',
        'you are my one and only.',
        'tryna smoke',
        'flow',
        'keeping myself healthy',
        'unfinished business...',
        'im afraid you wont accept me.',
        'i want to hold you in my arms and feel your skin next to mine.',
        'idc anymore, im calling texting you.',
        'cheap thrills?',
        'im aware i took advantage of the situation.',
        'trying to make this right.',
        'triggered.',
        'reflecting on what i did wrong and everythng you said...',
        'i was scared.',
        'not interested in being with anyone but you.',
        '1111',
        '222',
        'i want you to touch yourself and think of us.',
        'these niggas wont love you like i can.',
        'think of me.',
        'i want you so bad.',
        'the way you touch me makes me high.',
        'touching myself thinking of you.',
        'licking you all over.',
        'let me taste you again.',
        'you showed me real love.',
        'i think about all those things you said.',
        'did you mean it when you said that its mine?',
        'your body is out of this world',
        'the love i feel for you is real.',
        'the universe shows me signs that this connection is real.',
        'my spirits show me that you are the one.',
        'healing',
        'manifestation of goals',
        'delay, not denial',
        'wish coming true',
        'loving you is easy.',
        'you are so sensitive, i dont want to cause you harm.',
        'put me in my place.',
        'your level of kindness is rare.',
        'i miss how cute you are.',
        'your smile lights me up.',
        'the way you laugh...',
        'lucky femme',
        'ego boost',
        'i wanted you to chase me.',
        'will you accept or reject me?',
        'can i come over?',
        'i am ready.',
        'making room for us.',
        'i want to commit to us and prioritize this.',
        'twin flame, we belong together.',
        'i am worthy of this love.',
        'love me.',
        'dont you want me?',
        'im not upset.',
        'i will never forget that day.',
        'seeing you naked...',
        'swimming in those eyes...',
        'all i want is you.',
        'reaching out soon...',
        'spirit evolution',
        'unexpected changes',
        'i want to be absolutely sure that i am ready.',
        'i adore you and honor you.',
        'i cherish every moment we had together.',
        'real love',
        'you got me wrapped around your finger.',
        '555',
        'empress',
        'focus',
        'divine counterpart',
        'lovers',
        'star',
        'temperence',
        'your patience is a virtue.',
        'angelic support',
        '7',
        'divine intervention',
        'careful who you talk to about this connection.',
        'waking up next to you...',
        'faith in us',
        'teach me how to love.',
        'so sexy when you take control.',
        'i am waiting for the right time.',
        'i miss us.',
        'i miss you.',
        'si mami.',
        'you smell so good.',
        'kissing you...',
        'you make me a better person.',
        'making plans to come toward you...',
        'couldnt love you more.',
        'i am ashamed of how i treated you.',
        'dream girl',
        'i dream of you.',
        'i want to support you.',
        'no',
        'yes',
        'time and money',
        'i want to be good enough to pursue this.',
        'i dont want to hurt you.',
        'i know i have been inconsistent.',
        'you could have anyone you want.',
        'you deserve better than the way i did you.',
        'i ghosted and i regret it.'
    ][randomNumber];
}